#!/bin/zsh 

# mostly aliases along with other stuff i want to display at start up
alias epic=bat
alias cls=clear

# activate python env 
source /home/shanten/.jojobin/env/bin/activate


# Print section:
# last job: print le banner/other shit 
~/.jojobin/printbanner